### ISSUE TITLE
Can't aggregate based on `conn_id`

### ISSUE THREAD

**Issue by itshaadi** [ti-mo/conntracct#14]
Established and related state that are supported by iptables report the state of a connection in chunks. Therefore, a query like `sum("bytes_ret")` will not represent the actual file size. But rather it will sum the values reported in each Chunk.

Now, because `conn_id` is the same in each chunck, `last("conn_id"), bytes_ret` will return the exact file size that was downloaded.

However this action requires `conn_id` to be in `fields` because in some cases (like finding most visited destinations) you can't use `count(distinct("conn_id"))` on a tag.

But this approach has it's limitations too, like if I wanted to also measure the total bandwidth on a most visited destination it won't work, because it's not supported by influxdb (mixing aggregation with non-aggtegate).

So it would be nice if you could implement "destroy" state. It's supported by ulogd2 via `ulogd_inputflow_NFCT` plugin.

It basically reports the data once a connection has ended.

**Comment by ti-mo** [comment]
Hi @itshaadi, thanks for trying out the project! :muscle: I haven't tried what you're describing with InfluxDB, and I must admit I'm not very familiar with its query language when it comes to aggregations and transformations of data. (ironically, it's been a while since I seriously used Influx) Initially, I was only intending on using the influx sink for tracing, but with the implementation of the update rate curve, using it for long-term storage and visualization in InfluxDB is now much more feasible.

The use case you describe is something I'd definitely like to support. Could you boil down exactly what needs to be changed here? Is it a matter of a certain key being in `tags` but not in `fields`? (or vice versa?) Based on what I read, being able to discern ongoing and finished flows based on a `destroy` label would be handy, but you definitely need to take into account the latest `update` event for each conn_id as well, since there might be flows that last for days or more.

PS: also check out the elasticsearch driver I merged today. All documents inserted into elasticsearch carry a `destroy` or `update` event type accordingly. Same things holds true there, you also need to take into account large flows that did not yet finish.

**Comment by ti-mo** [comment]
In https://github.com/ti-mo/conntracct/commit/663d2d6e67bbd020b43e4b330f19fd6d3f05b29f I've added `conn_id` as a field, but kept it as a tag. This way, `conn_id` can be used in both aggregations and selections. The tag and the field value will be the same in every data point, so this should not cause any issues. I've also added the `bytes_total` and `packets_total` fields to avoid having to sum orig and ret.

Querying the amount of distinct conns for `connmark=3` and bytes consumed for `connmark=3` doesn't make much sense, split them up into different queries.

Amount of conns made per destination:
```
SELECT count(distinct(conn_id)) AS "conns" FROM "conntracct_http"."autogen"."ct_acct" WHERE connmark = '0' GROUP BY "dst_addr"
```
Total bytes per destination:
```
SELECT SUM(bytes_total)
FROM (
  SELECT LAST(bytes_total) AS bytes_total, bytes_orig, bytes_ret, src_addr, dst_addr, dst_port, proto, connmark, netns
  FROM "conntracct_http"."autogen"."ct_acct"
  GROUP BY "conn_id"
)
WHERE conn_id != ''
GROUP BY "dst_addr"
```

Note that the subquery here :point_up: takes the last data point in each `conn_id`'s series, so it takes into account both alive and destroyed flows.

Since InfluxDB is a timeseries database, it's not necessary to explicitly label points as originating from a 'destroy' event. When the destroy comes in, that final point is added to the series, and no more will follow.

Hope this helps!

**Comment by itshaadi** [comment]
thank you, this seems to be working correctly. I played around with your solution.

downloaded [go1.13.4.linux-amd64.tar.gz](https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz) (size on disk is 120054682 bytes) and `bytes_ret` was 124112342 it's much more accurate than before so I will say it's a success.

I'll leave you to decide on closing this issue.

PS: I assume that retrieved bytes should be equal or close to the actual size on disk. (in this instance there is 4MB overhead -- so the actual size on disk is 114MB and bytes_ret was 118MB)

**Comment by ti-mo** [comment]
Thanks for reporting back! The file size on disk is always going to be smaller than what's sent over the wire. Assuming you're transferring files over HTTP, there's the obvious HTTP headers, TCP/IP overhead in every packet, and if TLS is involved, you're paying some overhead there as well.

I will create a document with useful queries, and maybe add some wiki pages so this experience is smoother for new users.
